# Generated by Django 6.0.4 on 2026-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
    ]
